ProyectoUNSA/ProyectoUNSA/urls.py
from django.contrib import admin
from django.urls import path, include, reverse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simulador.urls')),
]

ProyectoUNSA/simulador/urls.py
from django.urls import path, include, reverse
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    path('', views.BienvenidaView.as_view(), name='bienvenida'),
    path('tablero/', views.tableroView, name='tablero'),
    path('inicio/', views.inicioView, name='inicio'),
    path('perfil/', views.perfilView, name='perfil'),
    path('perfilU/<int:pk>/', views.PostulanteUpdate.as_view(), name='perfilU'),
    path('examen/', views.examenView, name='examen'),
    path('examen2/', views.examen2View, name='examen2'),
    path('registrate/', views.SignUpView.as_view(), name='sign_up'),
    path('incia-sesion/', views.SignInView.as_view(), name='sign_in'),
    path('cerrar-sesion/', views.SignOutView.as_view(), name='sign_out'),
    path('preinscribir/<int:pk>/', views.preinscribir, name='preinscribir'),
    path('eliminarp/<int:pk1>/<int:pk2>/', views.eliminarp, name='eliminarp'),
    path('IngExamen/<int:pk>/', views.IngExamen, name='IngExamen'),
    path('prueba/<int:pk>/', views.Siguiente, name='examenentrada'),
    path('PFinal/<int:pk>/', views.PFinal, name = 'PFinal'),
    path('Final/<int:pk1>/<int:pk2>/<int:pk3>/', views.Final, name = 'Final'),
    #admin
    path('Administrador/', views.AdminView.as_view(), name = 'Administrador'),
    path('PList/', views.PostuanteList.as_view(), name = 'Plist'),
    path('PEdit/<int:pk>/', views.PostulanteEdit.as_view(), name = 'Pedit'),
    #User
    path('UDelete/<int:pk>/', views.UsuarioDelete.as_view(), name = 'Udelete'),
    path('Soluc/<int:pk>/', views.Solucionario.as_view(), name = 'Soluc'),
    # Cambiar contraseña
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/change_done.html'), name='password_change_done'),
    # Olvide mi contraseña
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_complete.html'), name='password_reset_complete'),
    #ExamenAdmin
    path('ExList', views.ExamenList.as_view(), name='Exlist'),
    path('ExDelete/<int:pk>/', views.ExamenDelete.as_view(), name='Exdelete'),
    path('ExCreate', views.ExamenCreate.as_view(), name= 'Excreate'),
    path('ExEdit/<int:pk>/', views.ExamenUpdate.as_view(), name= 'Exedit'),
    #Examen_Postulante
    path('ExPostList/<int:pk>/', views.Examen_PostulanteList.as_view(), name= 'ExPostlist'),
    path('ExPostCreate/<int:pk>/', views.Examen_PostulanteCreate.as_view(), name = 'ExPostcreate'),
    path('ExPostDelete/<int:pk>/', views.Examen_PostulanteDelete.as_view(), name = 'ExPostdelete'),
    #Examen_pregunta
    path('ExPregList/<int:pk>/', views.PreguntasList.as_view(), name = 'ExPreglist'),
    path('ExPregCreate/<int:pk>/', views.PreguntasCreate.as_view(), name = 'ExPregcreate'),
    path('ExPregDelete/<int:pk>/', views.PreguntaDelete.as_view(), name = 'ExPregdelete'),
]

ProyectoUNSA/simulador/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MaxValueValidator, MinValueValidator
#SPRINT 1
class Postulante(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=255, blank=True)
    web = models.URLField(blank=True)
    Numero_Examenes = models.IntegerField(default=0)
    Telefono = models.IntegerField(validators=[MaxValueValidator(999999999)], default=954347604)
    DNI = models.IntegerField(validators=[MaxValueValidator(99999999)], default=77777777)

    # Python 3
    def __str__(self):
        return self.usuario.username

@receiver(post_save, sender=User)
def crear_usuario_postulante(sender, instance, created, **kwargs):
    if created:
        Postulante.objects.create(usuario=instance)

@receiver(post_save, sender=User)
def guardar_usuario_postulante(sender, instance, **kwargs):
    instance.postulante.save()

#SPRINT 1
GEEKS_CHOICES =[
    ("O", "Ordinario"),
    ("C", "CEPRUNSA"),
    ("E", "Extraordinario"),
]
class Examen(models.Model):
    Tipo = models.CharField(max_length=100, choices=GEEKS_CHOICES, default='O')
    Fecha_Examen = models.DateTimeField(blank=False,null=False)
    Fecha_Resultados = models.DateTimeField(default=None,blank=True,null=True)
    Duracion = models.TimeField(default=0,blank=True,null=False)
    Estado = models.BooleanField(default=True)
    Nmro_Preguntas = models.IntegerField(default=80)
    soluciones = models.TextField(default="000000000000000000000000000000000000000000000000000000000000000000000000000000000")
    def __str__(self):
        return str(self.id)

class Area(models.Model):
    Nombre = models.CharField(max_length = 100, blank=True)
    def __str__(self):
        return self.Nombre

class Escuela(models.Model):
    Nombre = models.CharField(max_length = 100, blank=True)
    Vacantes = models.IntegerField()
    Area_id = models.ForeignKey(Area, on_delete=models.CASCADE, blank=False, null=False)
    def __str__(self):
        return self.Nombre

class Solucionario(models.Model):
    respuestas = models.TextField(default="000000000000000000000000000000000000000000000000000000000000000000000000000000000",blank=True,null=False)
    def save(self,*args,**kwargs):
        if Solucionario.objects.filter(pk=1).exists():
            #max_id = Solucionario.objects.all().order_by("-id")[0]
            conta = 1
            while Solucionario.objects.filter(pk=conta).exists():
                conta = conta +1
            self.id = conta
            #self.id=max_id.pk+1
        return super(Solucionario, self).save( *args, **kwargs)
    def act(self,sol,pos,*args,**kwargs):
        print("######################")
        solucion = self.respuestas
        print("######################")
        print(solucion)
        txt = ""
        for c in range(len(solucion)):
            if c == int(pos):
                txt = txt + str(sol)
                print(str(sol))
            else:
                txt = txt + solucion[c]
        print("######################")
        solucion = txt
        print("######################")
        print(solucion)
        EX = Solucionario.objects.filter(pk = self.pk).update(respuestas = solucion)
        self.respuestas = solucion
        #EX = Examen.objects.filter(pk=self.id_Examen.id).update(soluciones = solucion)
        return super(Solucionario, self).save( *args, **kwargs)


class Examen_Postulante(models.Model):
    Examen_id = models.ForeignKey(Examen, on_delete=models.CASCADE, blank=False, null=False)
    Postulante_id = models.ForeignKey(Postulante, on_delete=models.CASCADE, blank=False, null=False)
    Solucionario_id = models.ForeignKey(Solucionario, on_delete=models.CASCADE, blank=True, null=True, default=None)
    Nota = models.IntegerField(default=0)
    Escuela_id = models.ForeignKey(Escuela, on_delete=models.CASCADE, blank=False, null=False)
    Esta_inscrito = models.BooleanField(default=False)
    DioExamen = models.BooleanField(default=False)
    def __str__(self):
        return str(self.id)
    def save(self,*args,**kwargs):
        sol = Solucionario()
        sol.save()
        self.Solucionario_id = sol
        return super(Examen_Postulante, self).save( *args, **kwargs)
    def actualiza(self,sol,pos,*args,**kwargs):
        postulante_solucionario = Solucionario.objects.filter(pk = int(self.Solucionario_id.pk))
        print("========================")
        postulante_solucionario.first().act(sol,pos)
        print("========================")
        return super(Examen_Postulante, self).save( *args, **kwargs)
#SPRINT 2
class Pregunta(models.Model):
    Tema = models.CharField(max_length = 100,default="General")
    Enunciado = models.TextField(blank=False,null=False)
    E_imagen = models.ImageField(upload_to='photos',null=True,blank=True,default=None)
    sovle = models.IntegerField(default=1,blank=False, null=False)
    Resolucion = models.TextField(blank=True)
    Opcion1 = models.TextField(blank=False,null=False,default="No encontrado")
    Opcion2 = models.TextField(blank=False,null=False,default="No encontrado")
    Opcion3 = models.TextField(blank=False,null=False,default="No encontrado")
    Opcion4 = models.TextField(blank=False,null=False,default="No encontrado")
    Opcion5 = models.TextField(blank=False,null=False,default="No encontrado")
    O1_imagen = models.ImageField(upload_to='photos',null=True,blank=True,default=None)
    O2_imagen = models.ImageField(upload_to='photos',null=True,blank=True,default=None)
    O3_imagen = models.ImageField(upload_to='photos',null=True,blank=True,default=None)
    O4_imagen = models.ImageField(upload_to='photos',null=True,blank=True,default=None)
    O5_imagen = models.ImageField(upload_to='photos',null=True,blank=True,default=None)

class Esta_en_Examen(models.Model):
    id_Examen = models.ForeignKey(Examen, on_delete=models.CASCADE,blank=False,null=False)
    id_Pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE,blank=False,null=False)
    numero_pregunta = models.IntegerField(blank=True,null=False,default=1)
    def act(self,*args,**kwargs):
        EX = Examen.objects.filter(pk=self.id_Examen.id)
        solucion = EX.first().soluciones
        print(solucion)
        txt = ""
        for c in range(len(solucion)):
            if c == int(self.numero_pregunta):
                txt = txt + str(self.id_Pregunta.sovle)
                print(str(self.id_Pregunta.sovle))
            else:
                txt = txt + solucion[c]
        solucion = txt
        print(solucion)
        #EX.first().soluciones = solucion
        EX = Examen.objects.filter(pk=self.id_Examen.id).update(soluciones = solucion)
        #EX.save()
        return super(Esta_en_Examen, self).save( *args, **kwargs)

ProyectoUNSA/simulador/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Postulante, Examen_Postulante, Examen, Pregunta

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=140, required=True)
    last_name = forms.CharField(max_length=140, required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )

class Examen_PostulanteCreate(forms.ModelForm):
    class Meta:
        model = Examen_Postulante
        fields = '__all__'

class PostulanteForm(forms.ModelForm):
    class Meta:
        model = Postulante
        fields = (
            'Telefono',
            'DNI',
        )
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')
class UserForm2(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')

class ExamenForm(forms.ModelForm):
    class Meta:
        model= Examen
        fields = ("__all__")
class Examen_PostulanteForm(forms.ModelForm):
    class Meta:
        model = Examen_Postulante
        fields = ['Escuela_id', 'Postulante_id']

class PreguntaForm(forms.ModelForm):
    class Meta:
        model = Pregunta
        fields = ("__all__")

ProyectoUNSA/simulador/templates/simulador/Admin/Examen_postulante_form.html
{% extends "base_admin.html" %}
{% load static %}

{% block div %}
  <div class="container" style="text-align: center;">
    <form action="{% url 'ExPostcreate' 0 %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Save">
    </form>
  </div>
{% endblock div %}

{% block javascript %}

{% endblock javascript %}

ProyectoUNSA/simulador/templates/simulador/Admin/Examen_postulante_list.html
{% extends "base_admin.html" %}
{% load static %}

{% block div %}
<div class="row">
  <div class="col-sm-8">
    <h1>Postulantes inscritos</h1>
  </div>
  <div class="col-sm-4">
    <a href="{% url 'ExPostcreate' pk %}" type="submit" class="btn btn-info">Añadir Postulante</a>
  </div>
</div>
<table class="table  table-striped table-bordered table-sm">
  <thead>
    <tr>
      <th>#</th>
      <th>Postulante</th>
      <th>Escuela</th>
      <th>Estado</th>
      <th>#</th>
    </tr>
  </thead>
  <tbody>
  {% for i in object_list %}
  <tr>
    {% if i.Esta_inscrito %}
      {% if i.DioExamen %}
      <td>{{i.id}}</td>
      <td>{{i.Postulante_id.usuario.username}}</td>
      <td>{{i.Escuela_id.Nombre}}</td>
      <td>
        Inscrito
      </td>
      <td>
        <a href="{% url 'ExPostdelete' i.id %}" type="submit" class="btn btn-danger">Eliminar</a>
      </td>
      {% else %}
      <td>{{i.id}}</td>
      <td>{{i.Postulante_id.usuario.username}}</td>
      <td>{{i.Escuela_id.Nombre}}</td>
      <td>
        Dio el Examen
      </td>
      <td>
        <a href="{% url 'ExPostdelete' i.id %}" type="submit" class="btn btn-danger">Eliminar</a>
      </td>
      {% endif %}
    {% else %}
    <td>{{i.id}}</td>
    <td>{{i.Postulante_id.usuario.username}}</td>
    <td>{{i.Escuela_id.Nombre}}</td>
    <td>
      Pre-Inscrito
    </td>
    <td>
      <a href="{% url 'ExPostdelete' i.id %}" type="submit" class="btn btn-danger">Eliminar</a>
    </td>
    {% endif %}
  </tr>
  {% empty %}
  <p>No articles yet.</p>
  {% endfor %}
</tbody>
</table>
  <br>
  <a href="{% url 'Exlist' %}">Volver</a>
{% endblock %}

ProyectoUNSA/simulador/templates/simulador/Admin/Examen_pregunta_form.html
{% extends "base_admin.html" %}
{% load static %}

{% block div %}
  <div class="container" style="text-align: center;">
    <form action="{% url 'ExPregcreate' pk %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <p>Numero: <input type="number" name="numero_pregunta" required id="id_numero_pregunta"></p>
      <input type="submit" value="Save">
    </form>
  </div>
{% endblock div %}

{% block javascript %}

{% endblock javascript %}

ProyectoUNSA/simulador/templates/simulador/Admin/Examen_pregunta_list.html
{% extends "base_admin.html" %}
{% load static %}

{% block div %}
<div class="row">
  <div class="col-sm-8">
    <h1> Preguntas </h1>
  </div>
  <div class="col-sm-4">
    <a href="{% url 'ExPregcreate' pk %}" type="submit" class="btn btn-info">Añadir Pregunta</a>
  </div>
</div>
<table class="table  table-striped table-bordered table-sm">
  <thead>
    <tr>
      <th>#</th>
      <th>Enunciado</th>
      <th>Resolucion</th>
      <th>Opcion1</th>
      <th>Opcion2</th>
      <th>Opcion3</th>
      <th>Opcion4</th>
      <th>Opcion5</th>
      <th>#</th>
    </tr>
  </thead>
  <tbody>
  {% for i in object_list %}
  <tr>
    <td>{{i.id}}</td>
    <td>{{i.id_Pregunta.Enunciado}}</td>
    <td>{{i.id_Pregunta.Resolucion}}</td>
    <td>{{i.id_Pregunta.Opcion1}}</td>
    <td>{{i.id_Pregunta.Opcion2}}</td>
    <td>{{i.id_Pregunta.Opcion3}}</td>
    <td>{{i.id_Pregunta.Opcion4}}</td>
    <td>{{i.id_Pregunta.Opcion5}}</td>
    <td>
        <a href="{% url 'ExPregdelete' i.id %}" type="submit" class="btn btn-danger">Eliminar</a>
    </td>
  </tr>
  {% empty %}
  <p>No articles yet.</p>
  {% endfor %}
</tbody>
</table>
  <br>
  <a href="{% url 'Exlist' %}" class="btn btn-success">Volver</a>
{% endblock %}

ProyectoUNSA/simulador/templates/simulador/Admin/admin_bienvenida.html
{% extends "base_admin.html" %}
{% load static %}

{% block div %}
<table class="table">
    <tr><td>
        <a href="{% url 'Plist' %}" class="btn btn-primary">Postulantes</a>
    </td></tr>
    <tr><td>
        <a href="{% url 'Exlist' %}" class="btn btn-primary">Examenes</a>
    </td></tr>
    <tr><td>
        <a href="#" class="btn btn-primary">Areas</a>
    </td></tr>
</table>
{% endblock %}

ProyectoUNSA/simulador/templates/simulador/Admin/examen_form.html
{% extends "base_admin.html" %}
{% load static %}

{% block div %}
  <div class="container" style="text-align: center;">
    <form action="{% url 'Excreate' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <p>{{form.Tipo.label}}: {{form.Tipo}}</p>
      <p>{{form.Fecha_Examen.label}}: <input type="datetime-local" name="Fecha_Examen" required id="id_Fecha_Examen"></p>
      <p>{{form.Fecha_Resultados.label}}: <input type="datetime-local" name="Fecha_Resultados" required id="id_Fecha_Resultados"></p>
      <p>{{form.Duracion.label}}: <input type="time" name="Duracion" required id="id_Duracion"></p>
      <p>Numero de Preguntas: {{form.Nmro_Preguntas}}</p>
      <input type="submit" value="Save">
    </form>
  </div>
{% endblock div %}

{% block javascript %}

{% endblock javascript %}

ProyectoUNSA/simulador/templates/simulador/Admin/examen_list.html
{% extends "base_admin.html" %}
{% load static %}

{% block div %}
<div class="row">
    <div class="col-sm-8">
        <h1>Examenes</h1>
    </div>
    <div class="col-sm-4">
        <a href="{% url 'Excreate' %}" type="submit" class="btn btn-info">Añadir Examen</a>
    </div>
</div>
<div class="row">

<table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">#</th>
      <th class="th-sm">Tipo</th>
      <th class="th-sm">#</th>
      <th class="th-sm">#</th>
      <th class="th-sm">#</th>
      <th class="th-sm">#</th>
    </tr>
  </thead>
  <tbody>
    {% for i in object_list %}
    <tr>
      <td>{{i.id}}</td>
      <td>Examen {{i.get_Tipo_display}}</td>
      <td>
          <a href="{% url 'ExPreglist' i.id %}" type="submit" class="btn btn-primary">Preguntas</a>
      </td>
      <td>
          <a href="{% url 'ExPostlist' i.id %}" type="submit" class="btn btn-primary">Postulantes</a>
      </td>
      <td>
          <a href="{% url 'Exedit' i.id %}" type="submit" class="btn btn-warning">Editar</a>
      </td>
      <td>
          <a href="{% url 'Exdelete' i.id %}" type="submit" class="btn btn-danger">Eliminar</a>
      </td>
    </tr>
    {% empty %}
    <p>No articles yet.</p>
    {% endfor %}
  </tbody>
</table>
  <br>
  <a href="{% url 'Administrador' %}" class="btn btn-success">Volver</a>
</div>
<script>
  $(document).ready(function () {
  $('#dtBasicExample').DataTable({
  "ordering": false // false to disable sorting (or any other option)
  });
  $('.dataTables_length').addClass('bs-select');
  });
</script>
{% endblock %}

ProyectoUNSA/simulador/templates/simulador/Admin/examen_update_form.html
{% extends "base_admin.html" %}
{% load static %}

{% block div %}
  <div class="container" style="text-align: center;">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Save">
    </form>
  </div>
{% endblock div %}

{% block javascript %}

{% endblock javascript %}

ProyectoUNSA/simulador/templates/simulador/Admin/postulante_list.html
{% extends "base_admin.html" %}
{% load static %}

{% block div %}
<h1>Postulantes</h1>
<table class="table">
  <tr>
    <td>#</td>
    <td><h4>Postulante</h4></td>
    <td>#</td>
    <td>#</td>
  </tr>
  {% for i in object_list %}
  {% if i.usuario.is_staff %}
  {% else %}
  <tr>
    <td>{{i.id}}</td>
    <td>{{i.usuario.username}}</td>
    <td>
      <a href="{% url 'Pedit' i.id %}" type="submit" class="btn btn-warning">Editar</a>
    </td>
    <td>
        <a href="{% url 'Udelete' i.usuario.id %}" type="submit" class="btn btn-danger">Eliminar</a>
    </td>
  </tr>
  {% endif %}
  {% empty %}
  <p>No articles yet.</p>
  {% endfor %}
</table>
  <br>
  <a href="{% url 'Administrador' %}">Volver</a>
{% endblock %}

ProyectoUNSA/simulador/templates/simulador/Admin/postulante_update_form.html
{% extends 'base_admin.html' %}

{% block div %}
<br>
<br>
<br>
<div class="container" style="text-align: center;">
    <form action="{% url 'Pedit' 0 %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form2.as_p }}
        {{ form1.as_p}}
        <input type="submit" value="Actualizar">
    </form>
    <p><input type="button" value="Volver" onClick="history.go(-1);"></p>
</div>
{% endblock %}